# Generated by Django 4.0 on 2021-12-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='one_day_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of change')),
                ('close_value', models.FloatField()),
                ('symbol', models.CharField(max_length=12)),
            ],
        ),
    ]
