# Generated by Django 4.0 on 2022-05-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_investment_simulator', '0002_wallet_delete_one_day_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
