# Generated by Django 4.0 on 2022-05-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_investment_simulator', '0003_alter_wallet_key_alter_wallet_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='name',
            new_name='user_name',
        ),
    ]
