# Generated by Django 3.1.3 on 2022-04-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_investment_simulator', '0004_auto_20220427_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key_val',
            name='value',
            field=models.FloatField(db_index=True),
        ),
    ]
