# Generated by Django 3.1.3 on 2022-04-27 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_investment_simulator', '0005_auto_20220427_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='key',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='null', max_length=10), default='null', size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=100), default=-1, size=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='key_val',
        ),
    ]
