# Generated by Django 3.1.3 on 2022-04-27 14:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_investment_simulator', '0006_auto_20220427_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='key',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
