# Generated by Django 3.1.3 on 2022-04-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_investment_simulator', '0008_auto_20220427_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
